### PR TITLE
refactor: build via Cordova

### LINKED ISSUE #4: Replace CCA with Cordova
* [ ] Use new `cordova-plugin-` format

### LINKED ISSUE #5: Remove Chrome from build chain
* [ ] Grunt
* [ ] Linters

### LINKED ISSUE #12: Add Crosswalk
Likely part of #4

### PR DESCRIPTION
**Pull request by tlvince**
Depends on #40.

Closes #4, closes #5, closes #12.

### CODE REVIEW

**Comment by tlvince** [comment]
@karlwestin this is getting there; it works in a desktop browser, but does not pass the app config stage on Android. It seems to stall when pulling from the remote DBs.

**Comment by tlvince** [comment]
OK, two more issues:

* [x]: https://github.com/eHealthAfrica/move/issues/47
* [ ]: https://github.com/eHealthAfrica/move/issues/48

**Comment by tlvince** [comment]
@karlwestin this should be go to go, given your blessing.

**Comment by karlwestin** [comment]
@tlvince i don't understand, didn't we say we should use the build process from Sense Followup, to unify those? I'd much rather put some effort into separating that out to an npm module, and applying that on this app and one of the sense apps.

Also, i don't like the idea of managing cordova plugins via devDependencies in package.json, there are many cordova plugins that don't match the 'cordova-plugin-' pattern, and not having a separate place for them would create issues further down the road.

**Comment by tlvince** [comment]
The idea in this PR was to get it working in Cordova; we'll definitely extract the build process (here, I just dropped the scripts in), but as a separate task (#46). We can do that first if you want.

WRT, cordova-plugins, what issues do you foresee? Cordova are [closing their plugin registry](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html) soon to switch to npm. While rereading that, I noticed switching IDs to `cordova-plugin-` is optional (I thought it was mandatory), so you may have a point there, but some benefits of keeping them in package.json is they can be easily cached between builds and there's a single place for dependencies. Either way, this should probably be discussed in #46.

**Comment by karlwestin** [comment]
Ok i see your point
i started working on a separate build module with the scripts from sense followup.
ill hopefully submit a PR using that later today or tomorrow
Lets merge this as is meanwhile

**Comment by karlwestin** [comment]
Ok i see your point
i started working on a separate build module with the scripts from sense followup.
ill hopefully submit a PR using that later today or tomorrow
Lets merge this as is meanwhile

**Pull request merged**
