### PR TITLE
Refactor/show alert if validation fails

### LINKED ISSUE #120: on the incoming/outgoing deliveries, raise an error when a user is missing a field.
the application does not trigger a message that a field is missing. it just does not allow the user to save.

### PR DESCRIPTION
**Pull request by musamusa**
closes #120

### CODE REVIEW

**Comment by janetbutts** [comment]
@jofomah , please review.

**Comment by musamusa** [comment]
adding disabled (via css or ng-disabled) to the button will render ng-click useless

**Comment by jofomah** [comment]
if the button should be click-able, then why do we have to style it as a disabled button which are not click-able?

**Comment by musamusa** [comment]
@jofomah removed

**Pull request merged**
