### PR TITLE
Refactor/update chart after waste count

### LINKED ISSUE #109: waste: waste is not updating the stock chart

### PR DESCRIPTION
**Pull request by musamusa**
closes #109

### CODE REVIEW

**Comment by janetbutts** [comment]
@jofomah , please review asap. thanks!

**Comment by jofomah** [comment]
@musamusa finally, i don't think that the logic used in calculating waste count is correct IMHO:

it should be only consider waste counts since the last stock count, because if i recall correctly, stock level is calculated by `((latest stock count + incoming stock qtys since last stock count) - outgoing stock level since last stock count)`, waste stock level should only consider waste recorded since last stock count else the calculation won't be correct.

**Comment by jofomah** [comment]
@musamusa first of all what is the link is not what you are doing: am talking about using for loop instead of Object.keys(wasteCounts[i].reason[products[j]])).forEach() first of all it is confusing, you create an array of keys and then use forEach to loop over the array, why not loop over the array at once?

**Comment by musamusa** [comment]
Oh! sorry, I meant forEach() is still way faster than for in




*Musa Musam (ng): +234.809.776.6807skype: musakuntehttp://ehealthafrica.org
<http://ehealthafrica.org/>*

**Comment by jofomah** [comment]
well from the link you sent, it is not, for in takes 28ms while forEach() takes 51 ms. besides the way you are using forEach means you have to create an array first which has it own overhead and even after that from your link for in is still faster than forEach and the way you use the forEach is confusing.

**Comment by musamusa** [comment]
@jofomah, updated

**Comment by musamusa** [comment]
My understanding of waste count is that you can do it at any time any day as long as there is something to discard. What I did is to capture all waste count carried out within the stock count due period. unless there is a better way to capture the waste count count within stock count due period and not the exact date, then I'll like to go with that.

**Comment by jofomah** [comment]
What if the last stock count was two weeks ago, you updated calculation will pick only waste count recorded this week, whatever result you get will be incorrect because it won't consider waste count recorded two weeks ago meanwhile stock level is calculated by considering that stock count two week ago along with incoming and outgoing since the last stock count two weeks ago.

Now, i may be wrong but do you think considering only waste counts within current week will give you correct result, IMHO, waste count should consider all waste counts since last stock count, this stock count must not be within current week, it can be 3 week old.

**Comment by musamusa** [comment]
Something like subtracting reminder interval from the current due date and using the new interval to capture all waste count within the period. what do you think?

**Comment by jofomah** [comment]
@musamusa am not sure i understand what you mean but look at this line: https://github.com/eHealthAfrica/move/blob/develop/app/scripts/controllers/home.js#L151

Stock Level is calculated by considering incoming and outgoing legder since the mostRecentStockCount.modified date, now most recent in this case does not mean latest due stock count but the last stock count that was counted on the device. 

what am saying is for your calculation to be in line with this https://github.com/eHealthAfrica/move/blob/develop/app/scripts/controllers/home.js#L151

you need to retrieve all waste count that were created after `mostRecentCount.modified` so you have to retrieve all waste count whose created date is >= mostRecentCount.modified date.

**Comment by musamusa** [comment]
@jofomah, updated

**Comment by musamusa** [comment]
@jofomah updated

**Comment by musamusa** [comment]
@jofomah updated

**Comment by janetbutts** [comment]
@freefony , please review.

**Pull request merged**
