### PR TITLE
Remove a bunch of controllers + dependencies:

### PR DESCRIPTION
**Pull request by karlwestin**
app/scripts/controllers/stock-count-sync-stat.js
app/scripts/controllers/survey.js
app/scripts/controllers/programs.js
app/scripts/controllers/orders.js
app/scripts/controllers/facilities.js
app/scripts/controllers/batches.js

Batchservice is used by bundles and needed to stay

### CODE REVIEW

**Comment by jofomah** [comment]
@karlwestin LGTM, other possible  stale and unused files:

- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/companycategoryfactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/ccu-factory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/companycategoryfactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/companyfactory.js`
-  `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/currencyfactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/ordersfactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/programsfactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/settingsfactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/storageunittypefactory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/survey-factory.js`
- `https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/userfactory.js`

Should i merge this in or would you want to remove this ones and update PR?

**Comment by karlwestin** [comment]
let's take those as well while we're working on it! I'll have a look this afternoon!

**Comment by karlwestin** [comment]
Ok, i removed everything except the settingsFactory! To get rid of that one, i need to remove all 'settings' and 'dashboard' stuff in https://github.com/eHealthAfrica/move/blob/develop/app/scripts/controllers/home.js#L90-L362 - not quite sure what this stuff is, trying to figure out if it can go!

**Comment by jofomah** [comment]
@karlwestin dashboard.chart is used to show the chart you see on home page after login, but if it is somehow tied to setting......js then we can leave it for now. i know dashboard.chart is used for home page stock level chart.

**Comment by karlwestin** [comment]
@jofomah ready to merge?

**Comment by tlvince** [comment]
Ready?

**Comment by tlvince** [comment]
lgtm.

**Pull request merged**
