### PR TITLE
chore(i18n): Automate Transifex workflow

### LINKED ISSUE #30: Add grunt-tx
Add Grunt task to manage translations

### PR DESCRIPTION
**Pull request by rmehner**
Closes #30.

### CODE REVIEW

**Comment by karlwestin** [comment]
lgtm!

**Comment by rmehner** [comment]
Should I rebase and merge?

**Comment by karlwestin** [comment]
yess!

**Comment by tlvince** [comment]
Ready to merge?

**Comment by rmehner** [comment]
Yep, tests fail for another reason.

**Pull request merged**
