### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by karlwestin**
Authentication via the retriable module

### CODE REVIEW

**Comment by jofomah** [comment]
Look good, auth works fine.

comments:

- on fresh install, user is prompt to enter username and password, after that, i shows email address field again form configuring the app.
The ideas was to use email address (username) to load the app config so if they enter username and password, we can skip the enter email session and pull app config using the username(email) entered in the login dialog box,

- Seems background sync does not wait for promises to complete before returning, hence it logs sync completed but sync gets completed minutes later. 

- This one is not part of your PR, is an old bug i guess, i can't access App Config section while offline because it calls this https://github.com/eHealthAfrica/move/blob/develop/app/scripts/services/location-service.js#L36 which if it fails due to network connection blocks state transition.

Which reminds me of something that have bit me several times, if we resolve a promise inside state transition resolve block and it fails, state transition will not complete, work around is:

```Javascript
resolve: {
          appConfig: function(appConfigService) {
            return appConfigService.getCurrentAppConfig();
          },
          ccuProfilesGroupedByCategory: function(ccuProfileFactory) {
            return ccuProfileFactory.getAllGroupedByCategory();
          },
          productProfilesGroupedByCategory: function(productProfileFactory) {
            return productProfileFactory.getAllGroupedByCategory();
          },
          zones: function(locationService) {
            return locationService.getZones('f87ed3e017cf4f8db26836fd910e4cc8')
                  .catch(function(err){
                    /growl alert to user that 
                    return default value such as empty array or object etc
                  }) ;
          },
          lgaList: function(locationService) {
            return locationService.getLgas('f87ed3e017cf4f8db26836fd910e4cc8');
          },
          isEdit: function() {
            return true;
          }
        }

**Comment by karlwestin** [comment]
thanks @jofomah i addressed 1) and 2) of your comments now, 3) comes as a separate PR. 

Here's some test accounts if you wanna try:
user `wto.kwachiri_phc.fagge@kano.org.ng` (same login as all other accounts on dev)
is already configured, and goes straight to main screen.

user `zcco.nasarawa@kano.org.ng` is not configured yet, but their profile is fetched w/o repeating email step.

If you wanna see what happens when there are no profile, you can try the `slo` account

**Comment by jofomah** [comment]
@karlwestin great!, except that i cannot run fresh install twice, once i install once, even after i clear storage, on restart, the app automatically pulled the previous setup App config which is great but IMHO i think it should show the dialog box for confirmation or change of email address etc. What do you think?

**Comment by karlwestin** [comment]
@jofomah alright! I found another little routing/auth related bug that i fixed, just preventing the login modal to show twice

**Comment by jofomah** [comment]
ok, just let me know when it is ready!

**Comment by jofomah** [comment]
@karlwestin LGTM, clear storage bug fixed. :shipit: :+1:

**Pull request merged**
