### PR TITLE
chore(bower): bump Angular

### LINKED ISSUE #16: Update to Angular v1.4

### PR DESCRIPTION
**Pull request by tlvince**
Cursory look suggests nothing is broken.

Closes #16.

### CODE REVIEW

**Comment by karlwestin** [comment]
cool, just gonna check the changelog real quick

**Comment by karlwestin** [comment]
im getting this warning in the console, but it looks alright, so let's ignore that one
```
angular.js:12314 ngPluralize: no rule defined for 'NaN' in {
                        '0' : '{{bundleLine.quantity}} {{selectedProductBaseUOM[bundleLine.id]}}s',
                        '1' :'{{bundleLine.quantity}} {{selectedProductBaseUOM[bundleLine.id]}}',
                        'other':'{{bundleLine.quantity}} {{selectedProductBaseUOM[bundleLine.id]}}s'
                        }
```

Im gonna check whether this view was borked before

screen shot 2015-06-18 at 12 22 35

**Comment by karlwestin** [comment]
turns out that view was the same before

**Comment by tlvince** [comment]
Cool; lets open a separate issue for it

**Comment by tlvince** [comment]
Otherwise, good to merge?

**Comment by karlwestin** [comment]
yes! thanks for fixing this!

**Pull request merged**
