### PR TITLE
refactor: use packaged online-badge

### LINKED ISSUE #19: Add eha.online-badge
https://github.com/eHealthAfrica/angular-eha.online-badge

### PR DESCRIPTION
**Pull request by tlvince**
Depends on #68.

Closes #19.

### CODE REVIEW

**Comment by jofomah** [comment]
@tlvince i think the online badge has a bug, it works fine on web app but when compiled into a Cordova app, the online and offline toggling does not work fine, like if you go offline and come back online, sometimes the text shows online but the background is still red. we had this problem on LoMIS and what fixed it was using `===` in the online bagde template to decided what to show or hide refs https://github.com/eHealthAfrica/LMIS-Chrome/blob/develop/app/views/index/header.html

**Comment by tlvince** [comment]
Interesting. Will give it a spin.

**Comment by tlvince** [comment]
Tested an APK as of ce64b88 and didn't notice any issues; it responded to me switching off my phone's wifi fine.

**Comment by tlvince** [comment]
@karlwestin does this one look OK your end?

**Comment by karlwestin** [comment]
Just tested a build and the badge works fine for me. PR also lookin good!

**Pull request merged**
