### PR TITLE
Feature/create immunization summary sheet

### LINKED ISSUE #60: move PR/issue 584 - summary/kpi info from lmis-chrome to move repo

### PR DESCRIPTION
**Pull request by musamusa**
Closes #60

### CODE REVIEW

**Comment by janetbutts** [comment]
@freefony , please review

**Comment by janetbutts** [comment]
@freefony , review please

**Comment by freefony** [comment]
waiting for updates

**Comment by janetbutts** [comment]
this can wait until v. 12 is released.

**Pull request closed without merging**
